### ISSUE TITLE
Rendering crash on Jolla Tablet with prebuilt finnish offline maps

### ISSUE THREAD

**Issue by Termitebug** [Karry/osmscout-sailfish#9] opened 2016-10-30 11:28 UTC
Hi, here is a log file. The crash happens when you finger zoom too close and when too fast zooming in and out. The finnish map is downloaded from your Jolla Harbour link. Osmscout=0.11 and Sailfish=2.0.4.14.
[log.txt](https://github.com/Karry/osmscout-sailfish/files/560420/log.txt)

**Comment by Karry** [comment] 2016-10-31 17:21
Thanks for report! It is clear that application want access to `QList` item with invalid index. Unfortunately, I am not able to reproduce it on Jolla phone nor PC. It signalize that this problem is tablet specific. I review places where `QList` is used and it is possible that it is caused by gesture recognizer (emitted events depends on hardware driver). 

I added checks to possibly dangerous paths (if gesture event has empty list of points)... https://github.com/Karry/osmscout-sailfish/commit/6399873afdb9d685494848e6b12555587561a337
Can you install this build [harbour-osmscout-0.12-1.i486.rpm.zip](https://github.com/Karry/osmscout-sailfish/files/562426/harbour-osmscout-0.12-1.i486.rpm.zip) and try to reproduce it please?

**Comment by Termitebug** [comment] 2016-11-03 22:21
I'm so sorry for unable to answer until now. I have been too busy IRL. I tested your updated .rpm and I can't reproduce the issue anymore. And I agree this were affecting only Jolla Tablet. This can be closed if no more participants will appear saying otherwise.

**Comment by Karry** [comment] 2016-11-07 06:59
Once more time, thank you for testing. This fix is included in 0.12 release that will be available in Harbour soon (after Jolla QA process). Feel free to reopen this issue when it will be still there.

**Closed by Karry** 2016-11-07 06:59 UTC
