### ISSUE TITLE
Doesn't start after last update.

### ISSUE THREAD

**Issue by der-schultze** [Karry/osmscout-sailfish#211] opened 2020-04-20 14:07 UTC
Correction: On Jolla Tablet and Jolla 1 it runs now. But not on Sony.

On Sony Xperia X and also Jolla Tablet.
I tried to start via terminal on the Sony, see the output:

[D] main:112 - Usage of memory mapped files is supported.
[D] main:168 - Found storage: "/run/media/nemo/MOBILCARD32"
[D] main:177 - Install translator for locale  QLocale(German, Latin, Germany) / "de_DE"
[D] osmscout::Settings::loadOnlineTileProviders:146 - Loading online tile providers from  "/usr/share/harbour-osmscout/resources/online-tile-providers.json"
[D] osmscout::{anonymous}::loadResourceProviders:183 - Loading providers from  "/usr/share/harbour-osmscout/resources/map-providers.json"
[D] osmscout::{anonymous}::loadResourceProviders:183 - Loading providers from  "/usr/share/harbour-osmscout/resources/voice-providers.json"
[D] osmscout::MapManager::MapManager:240 - MapManager ctor
[D] MemoryManager::memoryLevelChanged:90 - Memory level: "normal"
[D] Storage::init:458 - Storage database opened: "/home/nemo/.local/share/harbour-osmscout/harbour-osmscout/storage.db"
[D] Storage::updateSchema:246 - last schema:  2
[W] osmscout::DBThread::onDatabaseListChanged:223 - Nodes data files can't be mmapped
[W] osmscout::DBThread::onDatabaseListChanged:234 - Areas data files can't be mmapped
[W] osmscout::DBThread::onDatabaseListChanged:245 - Ways data files can't be mmapped
[W] osmscout::DBThread::onDatabaseListChanged:256 - Router data files can't be mmapped
[D] osmscout::DBThread::onDatabaseListChanged:267 - Basemap found and loaded!
[D] MemoryManager::memoryLevelChanged:90 - Memory level: "normal"
[D] unknown:0 - Using Wayland-EGL
[D] unknown:0 - "No carrier"
[D] osmscout::MapWidget::loadSVGIcon:781 - Loaded icon "/usr/share/harbour-osmscout/map-icons/vehicle.svg"
[D] osmscout::MapWidget::loadSVGIcon:781 - Loaded icon "/usr/share/harbour-osmscout/map-icons/vehicle_not_fixed.svg"
[D] osmscout::MapWidget::loadSVGIcon:781 - Loaded icon "/usr/share/harbour-osmscout/map-icons/vehicle_tunnel.svg"
[D] osmscout::PlaneMapRenderer::~PlaneMapRenderer:78 - ~PlaneMapRenderer
[D] osmscout::MapRenderer::~MapRenderer:74 - ~MapRenderer
[D] osmscout::TileLoaderThread::TileLoaderThread:32 - Overlay tile cache: osmscout::TileCache(0xaedfb4)
[D] osmscout::TiledMapRenderer::Initialize:95 - Initialize
[D] onPositionValidChanged:172 - Positioning is valid
[D] onPositionValidChanged:173 - Last error 3
[D] onPositionValidChanged:174 - Last update Do. Jan. 1 01:00:00 1970 GMT+0100
[D] typeIcon:85 - Can't find icon for type 
[D] CollectionMapBridge::setMap:239 - CollectionMapBridge map: MapComponent_QMLTYPE_70(0xae7358, parent=0xae2600, geometry=0,0 0x0)
[D] IconProvider::requestPixmap:43 - Loading icon  "///usr/share/harbour-osmscout/pics/runner.svg"
[W] unknown:0 - QPainter::begin: Paint device returned engine == 0, type: 2
[W] unknown:0 - QPainter::save: Painter not active
[W] unknown:0 - QPainter::setPen: Painter not active
[W] unknown:0 - QPainter::setBrush: Painter not active
[W] unknown:0 - QPainter::setRenderHint: Painter must be active to set rendering hints
[W] unknown:0 - QPainter::setRenderHint: Painter must be active to set rendering hints
[W] unknown:0 - QPainter::brush: Painter not active
[W] unknown:0 - QPainter::setBrush: Painter not active
[W] unknown:0 - QPainter::opacity: Painter not active
[W] unknown:0 - QPainter::brush: Painter not active
[W] unknown:0 - QPainter::pen: Painter not active
[W] unknown:0 - QPainter::setPen: Painter not active
[W] unknown:0 - QPainter::setOpacity: Painter not active
[W] unknown:0 - QPainter::drawRects: Painter not active
[W] unknown:0 - QPainter::setPen: Painter not active
[W] unknown:0 - QPainter::setOpacity: Painter not active
[W] unknown:0 - QPainter::setBrush: Painter not active
[W] unknown:0 - QPainter::drawRects: Painter not active
[W] unknown:0 - QPainter::setBrush: Painter not active
[W] unknown:0 - QPainter::setOpacity: Painter not active
[W] unknown:0 - QPainter::setBrush: Painter not active
[W] unknown:0 - QPainter::brush: Painter not active
[W] unknown:0 - QPainter::setBrush: Painter not active
[W] unknown:0 - QPainter::worldTransform: Painter not active
[W] unknown:0 - QPainter::setWorldTransform: Painter not active
[W] unknown:0 - QPainter::opacity: Painter not active
[W] unknown:0 - QPainter::brush: Painter not active
[W] unknown:0 - QPainter::pen: Painter not active
[W] unknown:0 - QPainter::setPen: Painter not active
[W] unknown:0 - QPainter::setOpacity: Painter not active
[W] unknown:0 - QPainter::drawPath: Painter not active
[W] unknown:0 - QPainter::setPen: Painter not active
[W] unknown:0 - QPainter::setOpacity: Painter not active
[W] unknown:0 - QPainter::setBrush: Painter not active
[W] unknown:0 - QPainter::drawPath: Painter not active
[W] unknown:0 - QPainter::setBrush: Painter not active
[W] unknown:0 - QPainter::setOpacity: Painter not active
[W] unknown:0 - QPainter::setBrush: Painter not active
[W] unknown:0 - QPainter::setWorldTransform: Painter not active
[W] unknown:0 - QPainter::restore: Unbalanced save/restore
[W] unknown:0 - QPainter::end: Painter not active, aborted
[W] unknown:0 - QPainter::begin: Paint device returned engine == 0, type: 2
[W] unknown:0 - QPainter::setCompositionMode: Painter not active
[W] unknown:0 - QPainter::end: Painter not active, aborted
[W] unknown:673 - file:///usr/share/harbour-osmscout/qml/pages/MapPage.qml:673:13: QML Image: Failed to get image from provider: image://harbour-osmscout/pics/runner.svg?#ffffff
[D] IconProvider::requestPixmap:43 - Loading icon  "///usr/share/harbour-osmscout/routestep/information.svg"
[D] IconProvider::requestPixmap:43 - Loading icon  "///usr/share/harbour-osmscout/pics/compass.svg"
[W] unknown:0 - QPainter::begin: Paint device returned engine == 0, type: 2
[W] unknown:0 - QPainter::save: Painter not active
[W] unknown:0 - QPainter::translate: Painter not active
[W] unknown:0 - QPainter::scale: Painter not active
[W] unknown:0 - QPainter::setPen: Painter not active
[W] unknown:0 - QPainter::setBrush: Painter not active
[W] unknown:0 - QPainter::setRenderHint: Painter must be active to set rendering hints
[W] unknown:0 - QPainter::setRenderHint: Painter must be active to set rendering hints
[W] unknown:0 - QPainter::worldTransform: Painter not active
[W] unknown:0 - QPainter::setWorldTransform: Painter not active
[W] unknown:0 - QPainter::brush: Painter not active
[W] unknown:0 - QPainter::setBrush: Painter not active
[W] unknown:0 - QPainter::font: Painter not active
[W] unknown:0 - QPainter::setFont: Painter not active
[W] unknown:0 - QPainter::opacity: Painter not active
[W] unknown:0 - QPainter::setOpacity: Painter not active
[W] unknown:0 - QPainter::font: Painter not active
[W] unknown:0 - QPainter::worldTransform: Painter not active
[W] unknown:0 - QPainter::scale: Painter not active
[W] unknown:0 - QPainter::font: Painter not active
[W] unknown:0 - QPainter::pen: Painter not active
[W] unknown:0 - QPainter::brush: Painter not active
[W] unknown:0 - QPainter::pen: Painter not active
[W] unknown:0 - QPainter::setPen: Painter not active
[W] unknown:0 - QPainter::save: Painter not active
[W] unknown:0 - QPainter::setRenderHint: Painter must be active to set rendering hints
[W] unknown:0 - QPainter::pen: Painter not active
[W] unknown:0 - QPainter::pen: Painter not active
[W] unknown:0 - QPainter::setBrush: Painter not active
[W] unknown:0 - QPainter::setPen: Painter not active
[W] unknown:0 - QPainter::drawPath: Painter not active
[W] unknown:0 - QPainter::restore: Unbalanced save/restore
[W] unknown:0 - QPainter::pen: Painter not active
[W] unknown:0 - QPainter::setPen: Painter not active
[W] unknown:0 - QPainter::setPen: Painter not active
[W] unknown:0 - QPainter::setWorldTransform: Painter not active
[W] unknown:0 - QPainter::setOpacity: Painter not active
[W] unknown:0 - QPainter::setBrush: Painter not active
[W] unknown:0 - QPainter::setFont: Painter not active
[W] unknown:0 - QPainter::brush: Painter not active
[W] unknown:0 - QPainter::setBrush: Painter not active
[W] unknown:0 - QPainter::pen: Painter not active
[W] unknown:0 - QPainter::pen: Painter not active
[W] unknown:0 - QPainter::setPen: Painter not active
[W] unknown:0 - QPainter::opacity: Painter not active
[W] unknown:0 - QPainter::setOpacity: Painter not active
[W] unknown:0 - QPainter::opacity: Painter not active
[W] unknown:0 - QPainter::brush: Painter not active
[W] unknown:0 - QPainter::pen: Painter not active
[W] unknown:0 - QPainter::setPen: Painter not active
[W] unknown:0 - QPainter::setOpacity: Painter not active
[W] unknown:0 - QPainter::drawPath: Painter not active
[W] unknown:0 - QPainter::setPen: Painter not active
[W] unknown:0 - QPainter::setOpacity: Painter not active
[W] unknown:0 - QPainter::setBrush: Painter not active
[W] unknown:0 - QPainter::drawPath: Painter not active
[W] unknown:0 - QPainter::setBrush: Painter not active
[W] unknown:0 - QPainter::setOpacity: Painter not active
[W] unknown:0 - QPainter::setBrush: Painter not active
[W] unknown:0 - QPainter::setPen: Painter not active
[W] unknown:0 - QPainter::setOpacity: Painter not active
[W] unknown:0 - QPainter::brush: Painter not active
[W] unknown:0 - QPainter::setBrush: Painter not active
[W] unknown:0 - QPainter::pen: Painter not active
[W] unknown:0 - QPainter::pen: Painter not active
[W] unknown:0 - QPainter::setPen: Painter not active
[W] unknown:0 - QPainter::opacity: Painter not active
[W] unknown:0 - QPainter::setOpacity: Painter not active
[W] unknown:0 - QPainter::opacity: Painter not active
[W] unknown:0 - QPainter::brush: Painter not active
[W] unknown:0 - QPainter::pen: Painter not active
[W] unknown:0 - QPainter::setPen: Painter not active
[W] unknown:0 - QPainter::setOpacity: Painter not active
[W] unknown:0 - QPainter::drawPath: Painter not active
[W] unknown:0 - QPainter::setPen: Painter not active
[W] unknown:0 - QPainter::setOpacity: Painter not active
[W] unknown:0 - QPainter::setBrush: Painter not active
[W] unknown:0 - QPainter::drawPath: Painter not active
[W] unknown:0 - QPainter::setBrush: Painter not active
[W] unknown:0 - QPainter::setOpacity: Painter not active
[W] unknown:0 - QPainter::setBrush: Painter not active
[W] unknown:0 - QPainter::setPen: Painter not active
[W] unknown:0 - QPainter::setOpacity: Painter not active
[W] unknown:0 - QPainter::setWorldTransform: Painter not active
[W] unknown:0 - QPainter::restore: Unbalanced save/restore
[W] unknown:0 - QPainter::end: Painter not active, aborted
[W] unknown:0 - QPainter::begin: Paint device returned engine == 0, type: 2
[W] unknown:0 - QPainter::setCompositionMode: Painter not active
[W] unknown:0 - QPainter::end: Painter not active, aborted
[W] unknown:477 - file:///usr/share/harbour-osmscout/qml/pages/MapPage.qml:477:17: QML Image: Failed to get image from provider: image://harbour-osmscout/pics/compass.svg?#ffffff
[D] IconProvider::requestPixmap:43 - Loading icon  "///usr/share/harbour-osmscout/pics/compass.svg"
[D] onCompleted:95 - restore map position
[D] unknown:0 - Geoclue client path: "/org/freedesktop/Geoclue/Master/client13"
[D] CollectionMapBridge::onCollectionsLoaded:204 - Loaded 1 collections for map MapComponent_QMLTYPE_70(0xae7358, parent=0xae2600, geometry=0,0 1080x1920)
[D] IconProvider::requestPixmap:43 - Loading icon  "///usr/share/harbour-osmscout/pics/tracker.svg"
[D] osmscout::DBLoadJob::Run:110 - Skip database "/home/nemo/Maps/africa-south-africa-and-lesotho-20200227-224513"
[D] osmscout::DBLoadJob::Run:110 - Skip database "/home/nemo/Maps/africa-ghana-20200227-215030"
[D] osmscout::DBLoadJob::Run:110 - Skip database "/home/nemo/Maps/europe-czech-republic-20200229-004825"
[D] osmscout::DBLoadJob::Run:110 - Skip database "/home/nemo/Maps/africa-nigeria-20200227-223043"
[D] osmscout::OsmTileDownloader::download:76 - Download tile QUrl("https://osmscout.karry.cz/hillshade/tile.php?z=18&x=137732&y=88730") (current thread: QThread(0xafbbb0, name = "OverlayTileLoader") )
harbour-osmscout: /home/mersdk/share/SailfishOS/projects/osmscout-sailfish/dependencies/libosmscout/libosmscout/include/osmscout/TypeConfig.h:1055: const TypeInfoRef osmscout::TypeConfig::GetWayTypeInfo(osmscout::TypeId) const: Zusicherung »id<=wayTypes.size()« nicht erfüllt.

**Comment by Karry** [comment] 2020-04-20 21:07
Ups. It looks scary! I found recently one memory corruption issue, but it happens when cache is released, it is not your case... Which map database you have downloaded? Map directories are logged when you enable debug logs: `/usr/bin/harbour-osmscout --log debug` Can you try to update downloaded maps?

Another thing, can you generate core-dump and send it to me please? Just type to terminal:
```
ulimit -c unlimited
harbour-osmscout
```
then, when application crashes, it should generate `core.*` file in home directory... It would be great to provide it. Via some sharing service, send link to my e-mail lukas.karas@centrum.cz (core dump will contains whole process memory, including settings, cookies, application state...). Thanks

**Comment by der-schultze** [comment] 2020-04-21 07:07
Hi,

> Ups. It looks scary! I found recently one memory corruption issue, but it happens when cache is released, it is not your case... Which map database you have downloaded? Map directories are logged when you enable debug logs: /usr/bin/harbour-osmscout --log debug Can you try to update downloaded maps?

I will try, but how to update maps, when the app doesn't start?

Reported screen DPI: 446.52515
Map DPI override: 179.00000
Using stylesheet: /usr/share/harbour-osmscout/map-styles/standard.oss
Lookup databases
Checking database files in directory /home/nemo/Maps/africa-south-africa-and-lesotho-20200227-224513
found database Südafrika (mit Lesotho): /home/nemo/Maps/africa-south-africa-and-lesotho-20200227-224513
Checking database files in directory /home/nemo/Maps/africa-ghana-20200227-215030
found database Ghana: /home/nemo/Maps/africa-ghana-20200227-215030
Checking database files in directory /home/nemo/Maps/europe-czech-republic-20200229-004825
found database Tschechien: /home/nemo/Maps/europe-czech-republic-20200229-004825
Checking database files in directory /home/nemo/Maps/europe-great-britain-20200104-003048
found database Großbritannien: /home/nemo/Maps/europe-great-britain-20200104-003048
Checking database files in directory /home/nemo/Maps/africa-nigeria-20200227-223043
found database Nigeria: /home/nemo/Maps/africa-nigeria-20200227-223043
Checking database files in directory /home/nemo/Maps/europe-dach-20200301-074151
found database Deutschland, Österreich, Schweiz: /home/nemo/Maps/europe-dach-20200301-074151
BasemapDatabase::BasemapDatabase()
Database::Database()
TagRegistry::TagRegistry()
TypeConfig::TypeConfig()
Opening TypeConfig: 0.013
StyleConfig::StyleConfig()
Opening StyleConfig: 0.216
BoundingBox: [50.30972 S 12.31326 W - 10.32522 S 42.83769 E]
Opening BoundingBoxDataFile: 0.000
Database::Database()
TagRegistry::TagRegistry()
TypeConfig::TypeConfig()
Opening TypeConfig: 0.010
StyleConfig::StyleConfig()
Opening StyleConfig: 0.226
BoundingBox: [3.70406 N 3.93971 W - 11.37698 N 1.67302 E]
Opening BoundingBoxDataFile: 0.000
Database::Database()
TagRegistry::TagRegistry()
TypeConfig::TypeConfig()
Opening TypeConfig: 0.010
StyleConfig::StyleConfig()
Opening StyleConfig: 0.389
BoundingBox: [48.17392 N 11.58759 E - 51.31968 N 19.33828 E]
Opening BoundingBoxDataFile: 0.000
Database::Database()
TagRegistry::TagRegistry()
TypeConfig::TypeConfig()
Opening TypeConfig: 0.010
StyleConfig::StyleConfig()
Opening StyleConfig: 0.320
BoundingBox: [35.50040 N 25.20598 W - 65.36242 N 9.97576 E]
Opening BoundingBoxDataFile: 0.000
Database::Database()
TagRegistry::TagRegistry()
TypeConfig::TypeConfig()
Opening TypeConfig: 0.011
StyleConfig::StyleConfig()
Map DPI override: 179.00000
Map DPI override: 179.00000
Opening StyleConfig: 0.319
BoundingBox: [2.67402 N 2.13468 E - 14.42420 N 14.96552 E]
Opening BoundingBoxDataFile: 0.000
Database::Database()
TagRegistry::TagRegistry()
TypeConfig::TypeConfig()
Opening TypeConfig: 0.010
StyleConfig::StyleConfig()
Opening StyleConfig: 0.198
BoundingBox: [43.33204 N 20.07123 W - 62.51466 N 25.22325 E]
Opening BoundingBoxDataFile: 0.000
Opening WaterIndex: 0.001
Opening WaterIndex: 0.000
Opening WaterIndex: 0.000
Opening WaterIndex: 0.001
Opening WaterIndex: 0.000
Opening WaterIndex: 0.000
Opening OptimizeAreasLowZoom: 0.009
Opening OptimizeWaysLowZoom: 0.000
Opening AreaAreaIndex: 0.001
Opening AreaWayIndex: 0.001
Opening OptimizeAreasLowZoom: 0.002
Opening OptimizeWaysLowZoom: 0.000
Opening AreaWayIndex: 0.004
Opening AreaAreaIndex: 0.008
Opening AreaDataFile: 0.001
Opening WayDataFile: 0.000

That's all what I got with --log debug

**Comment by der-schultze** [comment] 2020-04-21 08:26
> then, when application crashes, it should generate core.* file in home directory... It would be great to provide it. Via some sharing service, send link to my e-mail lukas.karas@centrum.cz (core dump will contains whole process memory, including settings, cookies, application state...). Thanks

Do you need the whole file? It's about 150 MB. I can parse it through 'strings' and send the result by mail.

**Comment by Karry** [comment] 2020-04-21 12:23
> I will try, but how to update maps, when the app doesn't start?

good point :-) the only way would be to remove them from file browser and download them again...

> Do you need the whole file?

yes please. you may use https://ulozto.net/sem or similar file hosting service...

**Comment by der-schultze** [comment] 2020-04-21 12:34
> 

    I will try, but how to update maps, when the app doesn't start?

good point :-) the only way would be to remove them from file browser and download them again...

After I deleted all maps, the app is starting again.

**Comment by Karry** [comment] 2020-04-21 12:41
It was expected, because error happens during reading database... But it is still unknown if database is corrupted on the server (unlikely, I was not able to reproduced), corrupted on your phone (bug in downloader?) or there is bug in database reading...

**Comment by der-schultze** [comment] 2020-04-21 12:55
I sent you download link for the core.*** file

**Comment by Karry** [comment] 2020-04-21 13:53
Thank you! It seems that size of "/home/nemo/Maps/europe-dach-20200301-074151/ways.dat" file on your mobile was 1331 MiB, but it should have just 905 MiB. It seems that you downloaded this Dach database with very old version, because bug in downloader that was causing that (incorrect download re-establish) was fixed in version **1.12-1** that was released in June 2019... It is possible?

**Comment by der-schultze** [comment] 2020-04-21 14:02
Yes. Now I made the download of all maps again and app runs as expected.
Thank you

**Comment by Karry** [comment] 2020-04-21 14:05
Great! Closing it, it was caused by already fixed bug probably.

**Closed by Karry** 2020-04-21 14:05 UTC
